name: net-checks
releases:
- name: net-checks
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: netchecker
  azs:
  - z1
  lifecycle: errand
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: check-ports
    release: net-checks
    properties:
      port-check: ((tests))
